name: Selenium Test CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install selenium
        sudo apt update
        sudo apt install -y wget unzip

    - name: Install Google Chrome
      run: |
        sudo apt remove google-chrome-stable -y
        wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i chrome.deb || sudo apt-get -f install -y
        google-chrome --version

    - name: Install Correct ChromeDriver
      run: |
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.165/linux64/chromedriver-linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version

    - name: Run Selenium Test
      run: python test_login.py
      env:
        DISPLAY: ":99"
